"""
HackFarmer — GitHub push agent.
Creates a GitHub repo, pushes all generated files, builds ZIP,
uploads ZIP to Appwrite Storage, and emits job_complete.
"""

import logging
from datetime import datetime, timezone
from io import BytesIO

from appwrite.input_file import InputFile

from src.agents.state import ProjectState
from src.appwrite_client import databases, storage
from src.core.config import settings
from src.core.encryption import decrypt
from src.core.events import publish
from src.core.zip_builder import build_zip
from src.integrations.github import GitHubClient

log = logging.getLogger(__name__)
DB = settings.APPWRITE_DATABASE_ID


async def github_agent(state: ProjectState) -> dict:
    job_id = state["job_id"]
    user_id = state["user_id"]

    # Step 1: publish agent_start
    publish(job_id, "agent_start", {
        "agent": "github_agent",
        "message": "Pushing to GitHub...",
        "estimated_seconds": 20,
    })

    # Step 2: create AgentRun document
    agent_run_id = None
    try:
        doc = databases.create_document(DB, "agent-runs", "unique()", {
            "jobId": job_id,
            "agentName": "github_agent",
            "status": "running",
            "retryCount": 0,
            "startedAt": datetime.now(timezone.utc).isoformat(),
        })
        agent_run_id = doc["$id"]
    except Exception as e:
        log.warning(f"Failed to create agent-run doc: {e}")

    # Step 3: retrieve GitHub token from user document
    try:
        user_doc = databases.get_document(DB, "users", user_id)
        token = decrypt(user_doc["encryptedGhToken"])
        username = user_doc["username"]
    except Exception as e:
        error_msg = f"github_agent: Failed to retrieve GitHub credentials: {e}"
        publish(job_id, "agent_failed", {
            "agent": "github_agent", "error": error_msg, "retry_count": 0,
        })
        if agent_run_id:
            try:
                databases.update_document(DB, "agent-runs", agent_run_id, {
                    "status": "failed",
                    "completedAt": datetime.now(timezone.utc).isoformat(),
                })
            except Exception:
                pass
        return {"errors": state.get("errors", []) + [error_msg]}

    client = GitHubClient(token, username)
    repo_name = state.get("repo_name", state.get("project_name", "hackathon-project"))
    repo_private = state.get("repo_private", False)
    project_name = state.get("project_name", repo_name)

    # Step 4: create repo
    publish(job_id, "agent_thinking", {
        "agent": "github_agent",
        "message": "Creating repository...",
    })

    try:
        full_name = await client.create_repo(
            name=repo_name,
            description=f"{project_name} — generated by HackFarmer",
            private=repo_private,
        )
        github_url = f"https://github.com/{full_name}"
    except Exception as e:
        error_msg = f"github_agent: Failed to create repo: {e}"
        publish(job_id, "agent_failed", {
            "agent": "github_agent", "error": error_msg, "retry_count": 0,
        })
        if agent_run_id:
            try:
                databases.update_document(DB, "agent-runs", agent_run_id, {
                    "status": "failed",
                    "completedAt": datetime.now(timezone.utc).isoformat(),
                })
            except Exception:
                pass
        return {"errors": state.get("errors", []) + [error_msg]}

    # Step 5: push all generated files + README.md
    all_files = dict(state.get("generated_files", {}))
    readme = state.get("readme_content", "")
    if readme:
        all_files["README.md"] = readme

    publish(job_id, "agent_thinking", {
        "agent": "github_agent",
        "message": f"Pushing {len(all_files)} files...",
    })

    try:
        commit_sha = await client.push_files(
            repo=full_name,
            files=all_files,
            message="Initial commit — generated by HackFarmer 🚜",
        )
    except Exception as e:
        error_msg = f"github_agent: Failed to push files: {e}"
        publish(job_id, "agent_failed", {
            "agent": "github_agent", "error": error_msg, "retry_count": 0,
        })
        if agent_run_id:
            try:
                databases.update_document(DB, "agent-runs", agent_run_id, {
                    "status": "failed",
                    "completedAt": datetime.now(timezone.utc).isoformat(),
                })
            except Exception:
                pass
        return {
            "github_url": github_url,
            "errors": state.get("errors", []) + [error_msg],
        }

    # Step 6: build ZIP and upload to Appwrite Storage
    zip_file_id = None
    try:
        zip_bytes = build_zip(job_id, all_files)
        result = storage.create_file(
            bucket_id=settings.APPWRITE_ZIP_BUCKET_ID,
            file_id="unique()",
            file=InputFile.from_bytes(zip_bytes, filename=f"{repo_name}.zip"),
        )
        zip_file_id = result["$id"]
    except Exception as e:
        log.warning(f"ZIP upload failed (non-fatal): {e}")

    # Step 7: update job document
    try:
        update_data = {
            "status": "complete",
            "githubUrl": github_url,
            "completedAt": datetime.now(timezone.utc).isoformat(),
        }
        if zip_file_id:
            update_data["zipFileId"] = zip_file_id
        databases.update_document(DB, "jobs", job_id, update_data)
    except Exception as e:
        log.warning(f"Job update failed: {e}")

    # Step 8: update AgentRun + emit job_complete
    if agent_run_id:
        try:
            databases.update_document(DB, "agent-runs", agent_run_id, {
                "status": "done",
                "completedAt": datetime.now(timezone.utc).isoformat(),
                "outputSummary": f"Pushed {len(all_files)} files to {full_name}",
            })
        except Exception as e:
            log.warning(f"Failed to update agent-run doc: {e}")

    publish(job_id, "job_complete", {
        "github_url": github_url,
        "zip_file_id": zip_file_id or "",
        "file_count": len(all_files),
        "validation_score": state.get("validation_score", 0),
    })

    return {
        "github_url": github_url,
        "status": "complete",
    }
