export const AGENT_THEMES = {
  analyst: {
    label: "Analyst",
    character: "The Detective",
    tagline: "Hunting for truth in the specification",
    accentColor: "#3b82f6",
    bgFrom: "#0d1b2a",
    bgTo: "#091422",
    particleColor: "#1e40af",
    lottieFile: "detective",
    mediaFile: "/lottie/eH24xFv7I51NxX2V1K.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-blue",
    figurineStyle: "noir",
  },
  architect: {
    label: "Architect",
    character: "Blueprint Master",
    tagline: "Designing the system from ground up",
    accentColor: "#22c55e",
    bgFrom: "#0f1a12",
    bgTo: "#091409",
    particleColor: "#15803d",
    lottieFile: "blueprint",
    mediaFile: "/lottie/AA69SDr77h4z8E5D68.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-green",
    figurineStyle: "isometric",
  },
  frontend_agent: {
    label: "Frontend",
    character: "The Creative Designer",
    tagline: "Painting pixels into experiences",
    accentColor: "#a855f7",
    bgFrom: "#1a0d2e",
    bgTo: "#110820",
    particleColor: "#7c3aed",
    lottieFile: "designer",
    mediaFile: "/lottie/9DbbZ5bzP7Dr32q77O.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-purple",
    figurineStyle: "artistic",
  },
  backend_agent: {
    label: "Backend",
    character: "The Machine Engineer",
    tagline: "Building the engine under the hood",
    accentColor: "#f59e0b",
    bgFrom: "#1a1000",
    bgTo: "#120b00",
    particleColor: "#b45309",
    lottieFile: "gears",
    mediaFile: "/lottie/17vog9LfU253im8dm8.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-amber",
    figurineStyle: "industrial",
  },
  business_agent: {
    label: "Business",
    character: "The Pitch Strategist",
    tagline: "Crafting narratives that win judges",
    accentColor: "#ec4899",
    bgFrom: "#1a0a14",
    bgTo: "#120610",
    particleColor: "#be185d",
    lottieFile: "presentation",
    mediaFile: "/lottie/i1mqZ1H3ynm2urw4F7.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-pink",
    figurineStyle: "corporate",
  },
  integrator: {
    label: "Integrator",
    character: "The Weaver",
    tagline: "Merging all threads into one fabric",
    accentColor: "#14b8a6",
    bgFrom: "#001a1a",
    bgTo: "#001010",
    particleColor: "#0f766e",
    lottieFile: "weaver",
    mediaFile: "/lottie/ELzh3x62E1s4936hL4.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "dark-teal",
    figurineStyle: "organic",
  },
  validator: {
    label: "Validator",
    character: "The Professor",
    tagline: "Scoring every line with precision",
    accentColor: "#84cc16",
    bgFrom: "#0f1a0a",
    bgTo: "#0a1006",
    particleColor: "#4d7c0f",
    lottieFile: "professor",
    mediaFile: "/lottie/Learning Drawing.json",
    mediaType: "lottie",
    splineUrl: null,
    scrollTheme: "dark-lime",
    figurineStyle: "academic",
  },
  github_agent: {
    label: "GitHub",
    character: "The Astronaut",
    tagline: "Launching your code into the cosmos",
    accentColor: "#e2e8f0",
    bgFrom: "#080808",
    bgTo: "#000000",
    particleColor: "#334155",
    lottieFile: "rocket",
    mediaFile: "/lottie/uoEl8w3f4zCKaPN0Q3.webm",
    mediaType: "video",
    splineUrl: null,
    scrollTheme: "space",
    figurineStyle: "cosmic",
  },
};

